name: models
description: Models for QuadOS internals
version: 1.0.0
repository: https://github.com/Quad-Linux/models

environment:
    sdk: ^3.4.2

dependencies:
    freezed_annotation: ^2.4.4

dev_dependencies:
    build_runner: ^2.4.11
    freezed: ^2.5.7
    lints: ^3.0.0
    test: ^1.24.0
